const fs = require('fs');

const lines = fs.readFileSync('giornaliero.html', 'utf-8').split('\n');

const newLines = lines.slice(0, 413).concat([
'                    <!-- Monitoraggio Comportamentale (Live) -->',
'                    <div class="bg-tp-bg border border-tp-border rounded-xl p-4">',
'                        <label class="block text-[10px] font-bold uppercase tracking-widest text-tp-muted mb-4 border-b border-tp-border/50 pb-2 flex items-center justify-between">',
'                            <span>Registro Comportamentale (Invia ad Eventi)</span>',
'                        </label>',
'                        <div class="flex flex-col gap-4">',
'                            <div class="flex flex-wrap items-center gap-4">',
'                                <div class="flex flex-col gap-1.5">',
'                                    <span class="text-[9px] text-tp-muted font-bold uppercase tracking-widest">Stato Emotivo</span>',
'                                    <div class="flex items-center gap-1 bg-[#0a0c10] p-1 rounded-lg border border-tp-border shadow-inner">',
'                                        <button onclick="window.selectMindset(this, \'positive\')" class="mindset-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Focussed / Patient">',
'                                            <i data-lucide="smile" class="w-4 h-4"></i>',
'                                        </button>',
'                                        <button onclick="window.selectMindset(this, \'neutral\')" class="mindset-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Distratto / Neutro">',
'                                            <i data-lucide="meh" class="w-4 h-4"></i>',
'                                        </button>',
'                                        <button onclick="window.selectMindset(this, \'negative\')" class="mindset-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Frenetico / Emotivo">',
'                                            <i data-lucide="frown" class="w-4 h-4"></i>',
'                                        </button>',
'                                    </div>',
'                                </div>',
'                                <div class="flex flex-col gap-1.5">',
'                                    <span class="text-[9px] text-tp-muted font-bold uppercase tracking-widest">Volatilità Mercato</span>',
'                                    <div class="flex items-center gap-1 bg-[#0a0c10] p-1 rounded-lg border border-tp-border shadow-inner">',
'                                        <button onclick="window.selectVol(this, \'low\')" class="vol-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Bassa">',
'                                            <div class="flex"><i data-lucide="dollar-sign" class="w-4 h-4"></i></div>',
'                                        </button>',
'                                        <button onclick="window.selectVol(this, \'med\')" class="vol-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Media">',
'                                            <div class="flex"><i data-lucide="dollar-sign" class="w-4 h-4"></i><i data-lucide="dollar-sign" class="w-4 h-4 -ml-2"></i></div>',
'                                        </button>',
'                                        <button onclick="window.selectVol(this, \'high\')" class="vol-btn p-1.5 rounded-md text-tp-muted hover:bg-[#161920] transition-colors" title="Alta">',
'                                            <div class="flex"><i data-lucide="dollar-sign" class="w-4 h-4"></i><i data-lucide="dollar-sign" class="w-4 h-4 -ml-2"></i><i data-lucide="dollar-sign" class="w-4 h-4 -ml-2"></i></div>',
'                                        </button>',
'                                    </div>',
'                                </div>',
'                                <div class="flex flex-col gap-1.5 flex-1 min-w-[150px]">',
'                                    <span class="text-[9px] text-tp-muted font-bold uppercase tracking-widest">Tag Mindset</span>',
'                                    <select class="w-full bg-[#0a0c10] border border-tp-border rounded-lg px-2 py-1.5 text-xs focus:border-tp-accent outline-none text-white appearance-none cursor-pointer hover:border-tp-accent/50 transition-colors">',
'                                        <option value="" disabled selected>Seleziona focus...</option>',
'                                        <option value="focussed">⭐ Concentrato / Calmo</option>',
'                                        <option value="fomo">🔥 FOMO / Fretta</option>',
'                                        <option value="revenge">💣 Revenge Trading</option>',
'                                        <option value="tired">⚠️ Stanco / Confuso</option>',
'                                        <option value="bored">🥱 Annoiato / Overtrading</option>',
'                                    </select>',
'                                </div>',
'                            </div>',
'                            <div class="flex flex-col gap-1.5 mt-2">',
'                                <span class="text-[9px] text-tp-muted font-bold uppercase tracking-widest">Note di Apertura / Riflessioni su come mi sento</span>',
'                                <textarea class="w-full bg-[#0a0c10] border border-tp-border rounded-lg p-3 text-xs text-tp-text/90 outline-none min-h-[90px] resize-none placeholder-tp-muted/50 focus:border-tp-accent transition-colors shadow-inner" placeholder="Digita qui pensieri prima di affrontare i mercati..."></textarea>',
'                            </div>',
'                        </div>',
'                    </div>'
]).concat(lines.slice(444));

fs.writeFileSync('giornaliero.html', newLines.join('\n'), 'utf-8');
